### PR TITLE
Implement Windows support (issue #53)

### PR DESCRIPTION
**Pull request by matysek**
I tried to implement Windows support #53 
* It works for me.
* I tested it on Win7 / Python 3.4.3
* All tests pass for me on Windows and two are skipped because are not relevant for Windows.

### CODE REVIEW

**Comment by xolox** [comment]
Hi Martin and thanks for the effort you've put into this pull request!

It's funny, I was recently looking into AppVeyor for testing several of my Python projects on Windows (pip‑accel being one of those projects) and here you are wanting to run pip‑accel itself on AppVeyor just a few weeks later :-).

I'm planning to get this pull request merged this week. I've already started but won't finish it tonight and I thought I should let you know instead of leaving you waiting without feedback.

**Comment by xolox** [comment]
For posterity: I'm working on setting up [AppVeyor CI for pip-accel](https://ci.appveyor.com/project/xolox/pip-accel/history) because I don't want to claim support for a platform I can't actually test, I don't have access to any Windows systems and I don't feel like paying for a Windows license just so I can test an open source project. Fortunately AppVeyor is free for open source projects which is pretty cool :-).

**Comment by matysek** [comment]
@xolox This is appveyor project where I use `pip-accel`: https://ci.appveyor.com/project/matysek/pyinstaller

**Comment by xolox** [comment]
Hi again Martin,

After some intense Windows testing and debugging (last time I did that was quite a few years ago :-) I released pip-accel 0.33 to PyPI and GitHub. If you're interested in the additional changes I made (quite a few) you can take a look at pull request #61 (which included the changes from this pull request). If you encounter any further Windows issues feel free to open another issue.

Thanks for your contribution!

**Comment by matysek** [comment]
@xolox Thanks for integrating and cleaning up windows support.

**Pull request merged**
